---
# tasks file for ec2-provision

- name: EC2 DockerSWARM and ELK Automation
  ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         count: 1
         volumes:
         - device_name: /dev/sda1
           volume_size: 10
         vpc_subnet_id: subnet-f6c2689e
         assign_public_ip: no
         instance_tags:
          Name: sdc-{{item}}
  register: ec2
  with_items:
   - master
   - worker01
   - worker02

- name: Execute Internal IP to Hosts file script
  command: sh /opt/dockerswarm-elk-monitoring-automation/hosts.sh
